### ISSUE TITLE
Wirecube Does Not Reset Polygon Mode

### ISSUE THREAD

**Issue by Ronan-Rael** [jpaoneMines/csci441#43]
As the code for 3d object models is, the polygon mode for the front and the back of an object is reset separately from the frontback data member, leading to the wireframe polygon mode not getting reset to normal drawing after drawing a wireframe cube, leading to further cubes also being wireframe when they should not be.

**Comment by jpaoneMines** [comment]
This actually occurs for all the Wire objects.  The issue is with 

```
GLint currentPolygonMode[2];
glGetIntegerv(GL_POLYGON_MODE, currentPolygonMode);
glPolygonMode( GL_FRONT_AND_BACK, renderMode );
...
glPolygonMode( GL_FRONT, currentPolygonMode[0] );
glPolygonMode( GL_BACK, currentPolygonMode[1] );
```

Need to set `GL_FRONT_AND_BACK` when resetting the mode back.

**Comment by jpaoneMines** [comment]
fix staged for commit

**Comment by jpaoneMines** [comment]
The problem didn't present itself when drawing via the CSCI441 objects library since the front and back polygon mode was always being set.  

It was present if drawing occurred directly via glDrawElements() with a triangle primitive type and the front was set separately from the back, but not both together.
